stages:
  dataingestion:
    cmd: python src\data\dataingestion.py
    deps:
    - src\data\dataingestion.py
    outs:
    - data\raw\test.csv
    - data\raw\train.csv
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw/train.csv
    - src/data/data_preprocessing.py
    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  feature_engineering:
    cmd: python src/data/features.py
    deps:
    - data/processed/test.csv
    - data/processed/train.csv
    - src/data/features.py
    outs:
    - data/interim/test_bow.csv
    - data/interim/train_bow.csv
  model_training:
    cmd: python src/models/modelling.py
    deps:
    - data/interim/train_bow.csv
    - src/models/modelling.py
    outs:
    - models/random_forest_model.pkl
  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - data/interim/test_bow.csv
    - src/models/model_evaluation.py
    - models/random_forest_model.pkl
    outs:
    - reports/metrics.json
